import { describe, it, expect } from 'vitest';

import {
  generateId,
  _generateId,
  generateUUID,
  _generateUUID,
  isValidUUID,
  isValidProjectId,
} from '../idUtils';

describe('idUtils', () => {
  describe('generateId', () => {
    it('should generate a string with default prefix', () => {
      const id = generateId();
      expect(typeof id).toBe('string');
      expect(id.startsWith('id_')).toBe(true);
    });

    it('should generate a string with custom prefix', () => {
      const id = generateId('test');
      expect(typeof id).toBe('string');
      expect(id.startsWith('test_')).toBe(true);
    });

    it('should produce unique ids', () => {
      const ids = new Set(Array.from({ length: 100 }, () => generateId()));
      expect(ids.size).toBe(100);
    });

    it('should have timestamp and random components', () => {
      const id = generateId();
      const parts = id.split('_');
      expect(parts.length).toBe(3);
      // First part is prefix ('id'), second part is timestamp, third part is random
    });
  });

  describe('_generateId', () => {
    it('should directly generate a string with default prefix', () => {
      const id = _generateId();
      expect(typeof id).toBe('string');
      expect(id.startsWith('id_')).toBe(true);
    });

    it('should directly generate a string with custom prefix', () => {
      const id = _generateId('custom');
      expect(id.startsWith('custom_')).toBe(true);
    });
  });

  describe('generateUUID', () => {
    it('should generate a valid UUID string', () => {
      const uuid = generateUUID();
      expect(typeof uuid).toBe('string');
      // UUID format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx where y is 8, 9, a, or b
      expect(uuid).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    });

    it('should generate unique UUIDs', () => {
      const uuids = new Set(Array.from({ length: 100 }, () => generateUUID()));
      expect(uuids.size).toBe(100);
    });
  });

  describe('_generateUUID', () => {
    it('should directly generate a valid UUID string', () => {
      const uuid = _generateUUID();
      // UUID format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx where y is 8, 9, a, or b
      expect(uuid).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    });
  });

  describe('isValidUUID', () => {
    it('should validate correct UUIDs', () => {
      const validUUIDs = [
        '550e8400-e29b-41d4-a716-446655440000',
        '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
        '6ba7b811-9dad-11d1-80b4-00c04fd430c8',
        'f47ac10b-58cc-4372-a567-0e02b2c3d479',
      ];

      validUUIDs.forEach((uuid) => {
        expect(isValidUUID(uuid)).toBe(true);
      });
    });

    it('should reject invalid UUIDs', () => {
      const invalidUUIDs = [
        'project-1762812151532', // Custom ID format
        'proj_welcome_123456', // Demo project ID
        'not-a-uuid-at-all',
        '550e8400e29b41d4a716446655440000', // Missing dashes
        '550e8400-e29b-41d4-a716', // Too short
        '550e8400-e29b-41d4-a716-446655440000-extra', // Too long
        '', // Empty string
        'ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ', // Invalid characters
      ];

      invalidUUIDs.forEach((uuid) => {
        expect(isValidUUID(uuid)).toBe(false);
      });
    });

    it('should reject null and undefined', () => {
      expect(isValidUUID(null as any)).toBe(false);
      expect(isValidUUID(undefined as any)).toBe(false);
    });

    it('should reject non-string values', () => {
      expect(isValidUUID(123 as any)).toBe(false);
      expect(isValidUUID({} as any)).toBe(false);
      expect(isValidUUID([] as any)).toBe(false);
    });

    it('should validate UUIDs generated by generateUUID', () => {
      const uuid = generateUUID();
      expect(isValidUUID(uuid)).toBe(true);
    });
  });

  describe('isValidProjectId', () => {
    describe('UUID format (new standard)', () => {
      it('should accept valid UUIDs', () => {
        const validUUIDs = [
          '550e8400-e29b-41d4-a716-446655440000',
          '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
          'f47ac10b-58cc-4372-a567-0e02b2c3d479',
          generateUUID(), // Dynamically generated UUID
        ];

        validUUIDs.forEach((projectId) => {
          expect(isValidProjectId(projectId)).toBe(true);
        });
      });

      it('should accept UUIDs with different versions', () => {
        const uuidVersions = [
          '550e8400-e29b-11d4-a716-446655440000', // Version 1
          '550e8400-e29b-21d4-a716-446655440000', // Version 2
          '550e8400-e29b-31d4-a716-446655440000', // Version 3
          '550e8400-e29b-41d4-a716-446655440000', // Version 4
          '550e8400-e29b-51d4-a716-446655440000', // Version 5
        ];

        uuidVersions.forEach((projectId) => {
          expect(isValidProjectId(projectId)).toBe(true);
        });
      });
    });

    describe('Welcome project format (proj_welcome_*)', () => {
      it('should accept valid welcome project IDs', () => {
        const validWelcomeIds = [
          'proj_welcome_123456',
          'proj_welcome_1763045880279',
          'proj_welcome_0',
          `proj_welcome_${Date.now()}`, // Current timestamp
        ];

        validWelcomeIds.forEach((projectId) => {
          expect(isValidProjectId(projectId)).toBe(true);
        });
      });

      it('should reject malformed welcome project IDs', () => {
        const invalidWelcomeIds = [
          'proj_welcome_', // Missing timestamp
          'proj_welcome_abc', // Non-numeric timestamp
          'proj_welcome', // Missing underscore and timestamp
          'proj_welcomeabc', // Missing underscore separator
          'proj_welcome_123_extra', // Too many parts
        ];

        invalidWelcomeIds.forEach((projectId) => {
          expect(isValidProjectId(projectId)).toBe(false);
        });
      });
    });

    describe('Legacy format (project-{timestamp})', () => {
      it('should accept valid legacy project IDs', () => {
        const validLegacyIds = [
          'project-1763045880279', // Real example from production
          'project-1762812151532',
          'project-0',
          'project-123456789',
          `project-${Date.now()}`, // Current timestamp
        ];

        validLegacyIds.forEach((projectId) => {
          expect(isValidProjectId(projectId)).toBe(true);
        });
      });

      it('should reject malformed legacy project IDs', () => {
        const invalidLegacyIds = [
          'project-', // Missing timestamp
          'project-abc', // Non-numeric timestamp
          'project', // Missing dash and timestamp
          'project_123', // Wrong separator (underscore instead of dash)
          'project-123-extra', // Extra parts
          'project-12.34', // Decimal number
          'project--123', // Double dash
        ];

        invalidLegacyIds.forEach((projectId) => {
          expect(isValidProjectId(projectId)).toBe(false);
        });
      });
    });

    describe('Invalid formats', () => {
      it('should reject empty and invalid inputs', () => {
        expect(isValidProjectId('')).toBe(false);
        expect(isValidProjectId(null as any)).toBe(false);
        expect(isValidProjectId(undefined as any)).toBe(false);
        expect(isValidProjectId(123 as any)).toBe(false);
        expect(isValidProjectId({} as any)).toBe(false);
        expect(isValidProjectId([] as any)).toBe(false);
      });

      it('should reject completely invalid formats', () => {
        const invalidIds = [
          'random-string',
          'not-a-valid-id',
          '12345',
          'id_123_456', // generateId format (not a project ID)
          'chapter_abc',
          'ZZZZ-ZZZZ-ZZZZ-ZZZZ',
        ];

        invalidIds.forEach((projectId) => {
          expect(isValidProjectId(projectId)).toBe(false);
        });
      });
    });

    describe('Edge cases', () => {
      it('should handle very long timestamps in legacy format', () => {
        // JavaScript max safe integer: 9007199254740991
        expect(isValidProjectId('project-9007199254740991')).toBe(true);
      });

      it('should handle zero timestamp', () => {
        expect(isValidProjectId('project-0')).toBe(true);
        expect(isValidProjectId('proj_welcome_0')).toBe(true);
      });

      it('should be case-sensitive for UUID validation', () => {
        // UUIDs should be lowercase, but validator accepts both
        expect(isValidProjectId('550E8400-E29B-41D4-A716-446655440000')).toBe(true);
        expect(isValidProjectId('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
      });
    });

    describe('Real-world examples', () => {
      it('should accept real production project IDs', () => {
        // These are actual formats seen in production logs
        const realProjectIds = [
          'project-1763045880279', // Legacy format from error logs
          '6ba7b810-9dad-11d1-80b4-00c04fd430c8', // UUID format
          'proj_welcome_1762812151532', // Welcome project
        ];

        realProjectIds.forEach((projectId) => {
          expect(isValidProjectId(projectId)).toBe(true);
        });
      });
    });
  });
});
