import { describe, it, expect } from 'vitest';

import { generateId, _generateId, generateUUID, _generateUUID, isValidUUID } from '../idUtils';

describe('idUtils', () => {
  describe('generateId', () => {
    it('should generate a string with default prefix', () => {
      const id = generateId();
      expect(typeof id).toBe('string');
      expect(id.startsWith('id_')).toBe(true);
    });

    it('should generate a string with custom prefix', () => {
      const id = generateId('test');
      expect(typeof id).toBe('string');
      expect(id.startsWith('test_')).toBe(true);
    });

    it('should produce unique ids', () => {
      const ids = new Set(Array.from({ length: 100 }, () => generateId()));
      expect(ids.size).toBe(100);
    });

    it('should have timestamp and random components', () => {
      const id = generateId();
      const parts = id.split('_');
      expect(parts.length).toBe(3);
      // First part is prefix ('id'), second part is timestamp, third part is random
    });
  });

  describe('_generateId', () => {
    it('should directly generate a string with default prefix', () => {
      const id = _generateId();
      expect(typeof id).toBe('string');
      expect(id.startsWith('id_')).toBe(true);
    });

    it('should directly generate a string with custom prefix', () => {
      const id = _generateId('custom');
      expect(id.startsWith('custom_')).toBe(true);
    });
  });

  describe('generateUUID', () => {
    it('should generate a valid UUID string', () => {
      const uuid = generateUUID();
      expect(typeof uuid).toBe('string');
      // UUID format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx where y is 8, 9, a, or b
      expect(uuid).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    });

    it('should generate unique UUIDs', () => {
      const uuids = new Set(Array.from({ length: 100 }, () => generateUUID()));
      expect(uuids.size).toBe(100);
    });
  });

  describe('_generateUUID', () => {
    it('should directly generate a valid UUID string', () => {
      const uuid = _generateUUID();
      // UUID format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx where y is 8, 9, a, or b
      expect(uuid).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    });
  });

  describe('isValidUUID', () => {
    it('should validate correct UUIDs', () => {
      const validUUIDs = [
        '550e8400-e29b-41d4-a716-446655440000',
        '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
        '6ba7b811-9dad-11d1-80b4-00c04fd430c8',
        'f47ac10b-58cc-4372-a567-0e02b2c3d479',
      ];

      validUUIDs.forEach((uuid) => {
        expect(isValidUUID(uuid)).toBe(true);
      });
    });

    it('should reject invalid UUIDs', () => {
      const invalidUUIDs = [
        'project-1762812151532', // Custom ID format
        'proj_welcome_123456', // Demo project ID
        'not-a-uuid-at-all',
        '550e8400e29b41d4a716446655440000', // Missing dashes
        '550e8400-e29b-41d4-a716', // Too short
        '550e8400-e29b-41d4-a716-446655440000-extra', // Too long
        '', // Empty string
        'ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ', // Invalid characters
      ];

      invalidUUIDs.forEach((uuid) => {
        expect(isValidUUID(uuid)).toBe(false);
      });
    });

    it('should reject null and undefined', () => {
      expect(isValidUUID(null as any)).toBe(false);
      expect(isValidUUID(undefined as any)).toBe(false);
    });

    it('should reject non-string values', () => {
      expect(isValidUUID(123 as any)).toBe(false);
      expect(isValidUUID({} as any)).toBe(false);
      expect(isValidUUID([] as any)).toBe(false);
    });

    it('should validate UUIDs generated by generateUUID', () => {
      const uuid = generateUUID();
      expect(isValidUUID(uuid)).toBe(true);
    });
  });
});
