export const CONSTANTS = {
  MESSAGE_LIMIT: 50,
  AUTO_SAVE_INTERVAL: 30000,
  STORAGE_KEY: 'complete-writing-platform-v2',
  DEFAULT_TARGET_WORDS: 80000,
  CONFLICT_AGE_THRESHOLD: 1,
  DEBOUNCE_DELAY: 300,
  MAX_TIMELINE_EVENTS: 1000,
};
