name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm so it's on PATH
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Set up Node and enable pnpm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        shell: bash
        run: |
          pnpm run -s lint || pnpm run -s lint:relaxed

      - name: Typecheck
        run: pnpm run -s typecheck

      - name: Build
        run: pnpm run -s build

      - name: Test
        run: pnpm run -s test
