name: lint
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ensure pnpm is actually installed on PATH
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      # Pick whichever script you prefer; --if-present avoids hard failures
      - name: Lint
        run: pnpm run lint --if-present || pnpm run lint:relaxed --if-present
