name: Lint • Typecheck • Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Node + cache for pnpm (looks for pnpm-lock.yaml)
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      # Install deps from lockfile
      - run: pnpm install --frozen-lockfile

      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm build
